server:
  log_level: info

metrics:
  global:
    scrape_interval: 15s
    remote_write:
    - url: <YOUR CLOUD METRICS URL>
      basic_auth:
        username: "<YOUR CLOUD METRICS USERNAME>"
        password: "<YOUR CLOUD METRICS PASSWORD>"
  configs:
  - name: default
    scrape_configs:
    - job_name: "prusa"
      static_configs:
        - targets: ["exporter:10009"]

logs:
  positions_directory: /var/lib/grafana-agent
  configs:
  - name: prusa
    clients:
    - url: <url>
    scrape_configs:
    - job_name: system
      pipeline_stages:
      static_configs:
      - labels:
          job: varlogs
          __path__: /var/log/*.log
    - job_name: prusa_syslog
      pipeline_stages:
        - json:
            expressions:
              message:
              stream:
              time:
              level:
              app_name:
              client:
              hostname:
        - labels:
            stream:
            time:
            level:
            app_name:
            client:
            hostname:
        - output:
            source: message
      static_configs:
      - labels:
          stream: 'stdout'
          job: prusa_printers_logs
          __path__: /var/log/prusa/exporter.log

integrations:
  agent:
    enabled: true
  node_exporter:
    enabled: true