server:
  log_level: info

metrics:
  global:
    scrape_interval: 15s
    remote_write:
    - url: <YOUR CLOUD METRICS URL>
      basic_auth:
        username: "<YOUR CLOUD METRICS USERNAME>"
        password: "<YOUR CLOUD METRICS PASSWORD>"
  configs:
  - name: default
    scrape_configs:
    - job_name: "prusa"
      static_configs:
        - targets: ["exporter:10009"]

logs:
  positions_directory: /var/lib/grafana-agent
  configs:
  - name: prusa_exporter_logs
    clients:
    - url: <url>
    scrape_configs:
    - job_name: prusa_syslog__push
      loki_push_api:
        server:
          http_listen_port: 3500
        labels:
          pushserver: log_push
    
integrations:
  agent:
    enabled: true
  node_exporter:
    enabled: true