exporter:
  metrics_port: 10009 # exporter port
  scrape_timeout: 1 # scrape timeout of Prusa Link
  reload_interval: 300 # interval in seconds for config reloader
  log_level: info
  syslog_metrics: true # WARNING: EXPERIMENTAL FEATURE
  syslog_port: 10008
printers:
  buddy:
  - address: <address_of_printer>
    username: maker 
    pass: <password>
    name: <your_printer_name>
  - address: <address_of_printer>
    username: maker
    pass: <password>
    name: <your_printer_name>
  einsy:
  - address: <address_of_printer>
    username: maker 
    pass: <password>
    name: <your_printer_name>
  - address: <address_of_printer>
    username: maker
    pass: <password>
    name: <your_printer_name>