version: "3"

networks:
  prusa:

services:
  exporter:
    image: pubeldev/prusa_exporter:v0.9.2
    container_name: exporter
    restart: unless-stopped
    volumes:
      - type: bind
        source: /boot/firmware/prusa.yml
        target: /app/prusa.yml
    ports:
      - "10009:10009"
    command: '--config.file=/app/prusa.yml'
    networks:
      - prusa
  agent:
    image: grafana/agent:v0.39.2
    container_name: grafana_agent
    restart: unless-stopped
    volumes:
      - type: bind
        source: /boot/firmware/agent.yaml
        target: /etc/agent-config/agent.yaml
    entrypoint:
      - /bin/grafana-agent
      - -server.http.address=0.0.0.0:12345
      - -config.file=/etc/agent-config/agent.yaml
      - -metrics.wal-directory=/tmp/agent/wal
    ports:
      - "12345:12345"
    networks:
      - prusa
    depends_on:
      - exporter
  
