version: "3"

networks:
  prusa:

volumes:
  prometheus_data:
services:
  node-exporter:
    image: prom/node-exporter:v1.5.0
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - "9100:9100"
    networks:
      - prusa

  prometheus:
    image: prom/prometheus:v2.37.7
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./docs/examples/config/on_premise/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--storage.tsdb.retention.time=1d'
    ports:
      - "9090:9090"
    networks:
      - prusa

  promtail:
    image: grafana/promtail:2.8.0
    container_name: promtail
    volumes:
      - ./docs/examples/config/on_premise/promtail.yaml:/etc/promtail/config.yml
      - /var/log:/var/log
    command: '--config.file=/etc/promtail/config.yml'
    networks:
      - prusa

  exporter:
    image: pubeldev/prusa_exporter:latest
    container_name: exporter
    volumes:
      - type: bind
        source: ./docs/examples/config/on_premise/prusa.yml
        target: /app/prusa.yml
    ports:
      - "10009:10009"
    command: '--config.file=/app/prusa.yml'
    networks:
      - prusa
