version: "3"

networks:
  prusa:

volumes:
  mimir_data:
  grafana_data:
  prusa_syslog_logs:

services:
  loki:
    image: grafana/loki:2.9.6
    container_name: loki
    volumes:
      - ./docs/examples/config/on_premise/loki.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - prusa

  mimir:
    image: grafana/mimir:latest
    command: ["-config.file=/etc/mimir.yaml"]
    hostname: mimir
    volumes:
      - ./config/mimir.yaml:/etc/mimir.yaml
      - ./config/alertmanager-fallback-config.yaml:/etc/alertmanager-fallback-config.yaml
      - mimir-data:/data

  grafana:
    image: grafana/grafana:10.3.5
    container_name: grafana
    depends_on:
      - loki
      - mimir
    ports:
      - "3000:3000"
    networks:
      - prusa
    volumes:
      - grafana_data:/var/lib/grafana

  exporter:
    image: pubeldev/prusa-exporter:v1.0.rc1
    container_name: exporter
    restart: unless-stopped
    volumes:
      - prusa_syslog_logs:/var/log/prusa
      - type: bind
        source: /boot/firmware/prusa.yml
        target: /app/prusa.yml
    ports:
      - "10007:10007/udp"
      - "10008:10008/udp"
      - "10009:10009"
    command: '--config.file=/app/prusa.yml'
    networks:
      - prusa

  agent:
    image: grafana/agent:v0.39.2
    container_name: grafana_agent
    depends_on:
      - exporter
      - mimir
    restart: unless-stopped
    volumes:  
      - /var/run/docker.sock:/var/run/docker.sock
      - prusa_syslog_logs:/var/log/prusa
      - type: bind
        source: /boot/firmware/agent.yaml
        target: /etc/agent-config/agent.yaml
    entrypoint:
      - /bin/grafana-agent
      - -server.http.address=0.0.0.0:12345
      - -config.file=/etc/agent-config/agent.yaml
      - -metrics.wal-directory=/tmp/agent/wal
    networks:
      - prusa