apiVersion: 1

datasources:
  - name: Mimir
    type: prometheus
    uid: mimir
    access: proxy
    orgId: 1
    url: http://mimir:9009/prometheus
    version: 1
    editable: true
    isDefault: true
    jsonData:
      prometheusType: Mimir
  - name: Loki
    type: loki
    uid: loki
    access: proxy
    orgId: 1
    editable: true
    url: http://loki:3100