{
 "title": "Prusa Syslog - Logs",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "printer_mac",
    "label": "MAC",
    "query": {}
   },
   {
    "name": "printer_ip",
    "label": "IP",
    "query": {}
   },
   {
    "name": "severity",
    "label": "Severity",
    "query": {}
   },
   {
    "name": "proc_id",
    "label": "Proc ID",
    "query": {}
   },
   { "name": "searchable_pattern", "label": "Log Search (case insensitive)" }
  ]
 },
 "panels": [
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Printer Logs Count by proc_id",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({hostname=\"$printer_mac\"})[$__range])) by (proc_id)",
     "legendFormat": "{{proc_id}}"
    }
   ]
  },
  {
   "title": "Printer Logs Count by severity",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({hostname=\"$printer_mac\"})[$__range])) by (severity)",
     "legendFormat": "{{severity}}"
    }
   ]
  },
  {
   "title": "Count over time",
   "type": "timeseries",
   "description": "Total Count of log lines in the specified time range",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(count_over_time(({hostname=\"$printer_mac\", proc_id=~\"$proc_id\", severity=~\"$severity\"} |~ \"(?i)$searchable_pattern\"  )[$__range]))"
    }
   ]
  },
  {
   "title": "Printer Logs",
   "type": "logs",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "{hostname=\"$printer_mac\", proc_id=~\"$proc_id\", severity=~\"$severity\"}"
    }
   ]
  }
 ]
}