exporter:
  scrape_timeout: 1000 # scrape timeout of Prusa Link in ms
  log_level: info
  prusalink:
    enabled: true
  syslog:
    metrics:
      enabled: true
      listen_address: 0.0.0.0:10008
    logs:
      enabled: true
      listen_address: 0.0.0.0:10007
      directory: /var/log/prusa
      filename: exporter.log
      max_size: 10 # in MB
      max_age: 7 # in days
      max_backups: 10
printers:
  - address: <address_of_printer>
    username: maker
    password: <password>
    name: <your_printer_name> # optional
    type: MINI # or MK35 / MK39 / MK4 / XL / IX
  - address: <address_of_printer>
    apikey: <apikey>
    name: <your_printer_name> # optional
    type: I3MK25 # or I3MK25S / I3MK3 / I3MK3S