exporter:
  metrics_port: 10009 # exporter port
  scrape_timeout: 1 # scrape timeout of Prusa Link
  reload_interval: 300 # interval in seconds for config reloader
  log_level: info
  syslog:
    metrics:
      enabled: true
      listen_udp: 0.0.0.0:10008
    logs:
      enabled: true
      listen_udp: 0.0.0.0:10007
      loki_endpoint: http://agent:3500
printers:
  buddy:
  - address: <address_of_printer>
    username: maker 
    pass: <password>
    name: <your_printer_name>
  - address: <address_of_printer>
    username: maker
    pass: <password>
    name: <your_printer_name>
  einsy:
  - address: <address_of_printer>
    apikey: <apikey>
    name: <your_printer_name>