exporter:
  scrape_timeout: 1 # scrape timeout of Prusa Link
  reload_interval: 300 # interval in seconds for config reloader
  log_level: info
  prusalink:
    enabled: true
  syslog:
    metrics:
      enabled: true
      listen_address: 0.0.0.0:10008
    logs:
      enabled: true
      listen_address: 0.0.0.0:10007
      path: ./ #local path to store logs, default
      filename: prusa.log
printers:
  - address: <address_of_printer>
    username: maker
    password: <password>
    name: <your_printer_name> # optional
  - address: <address_of_printer>
    apikey: <apikey>
    name: <your_printer_name> # optional